import os

os.environ.setdefault("ENVIRONMENT", "dev")
os.environ.setdefault("GUILD_ID", "1")
os.environ.setdefault("BOT_TOKEN", "x")
os.environ.setdefault("WOM_GROUP_ID", "1")
os.environ.setdefault("WOM_API_KEY", "x")
os.environ.setdefault("AUTOMATION_CHANNEL_ID", "1")
os.environ.setdefault("RAFFLE_CHANNEL_ID", "1")
os.environ.setdefault("INGOT_SHOP_CHANNEL_ID", "1")
os.environ.setdefault("RULES_CHANNEL_ID", "1")
os.environ.setdefault("RANKINGS_CHANNEL_ID", "1")
os.environ.setdefault("BOT_COMMANDS_CHANNEL_ID", "1")
os.environ.setdefault("BOT_CHANGELOG_CHANNEL_ID", "1")
os.environ.setdefault("CREATE_TICKET_CHANNEL_ID", "1")
