"""add role field to member

Revision ID: 12c509b3fd8c
Revises: ff14108b4c64
Create Date: 2026-01-25 15:54:47.196276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c509b3fd8c'
down_revision: Union[str, None] = 'ff14108b4c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('BANNED', 'GUEST', 'APPLICANT', 'PROSPECT', 'MEMBER', 'BOOSTER', 'BLACKLISTED', 'MODERATOR', 'STAFF', 'BRIGADIER', 'ADMIRAL', 'LEADERSHIP', 'MARSHAL', 'OWNER', name='role', native_enum=False), nullable=False, server_default='GUEST'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
