"""initial migration

Revision ID: 5588232465b1
Revises:
Create Date: 2025-07-28 18:59:03.455915

"""

from typing import Sequence, Union

from ironforgedbot.models.decorators import UTCDateTime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5588232465b1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("nickname", sa.String(length=12), nullable=False),
        sa.Column("ingots", sa.Integer(), nullable=False),
        sa.Column(
            "rank",
            sa.Enum(
                "GOD_ZAMORAK",
                "GOD_GUTHIX",
                "GOD_SARADOMIN",
                "GOD",
                "MYTH",
                "LEGEND",
                "DRAGON",
                "RUNE",
                "ADAMANT",
                "MITHRIL",
                "IRON",
                name="rank",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("joined_date", UTCDateTime(), nullable=False),
        sa.Column("last_changed_date", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "changelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("admin_id", sa.String(length=36), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "ADD_MEMBER",
                "NAME_CHANGE",
                "ACTIVITY_CHANGE",
                "JOINED_DATE_CHANGE",
                "RESET_INGOTS",
                "ADD_INGOTS",
                "REMOVE_INGOTS",
                "RANK_CHANGE",
                "PURCHASE_RAFFLE_TICKETS",
                name="changetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("previous_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.String(length=255), nullable=True),
        sa.Column("timestamp", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raffle_tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("last_changed_date", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raffle_tickets")
    op.drop_table("changelog")
    op.drop_table("members")
    # ### end Alembic commands ###
