"""Initial Migration

Revision ID: 5aaeb8c99410
Revises:
Create Date: 2025-03-18 20:14:58.966173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from ironforgedbot.models.decorators import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "5aaeb8c99410"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "members",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("discord_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("ingots", sa.Integer(), nullable=False),
        sa.Column("rank", sa.String(), nullable=False),
        sa.Column("joined_date", UTCDateTime(), nullable=False),
        sa.Column(
            "last_changed_date",
            UTCDateTime(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "changelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(), nullable=False),
        sa.Column("admin_id", sa.String(), nullable=True),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("previous_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("timestamp", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raffle_tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "last_changed_date",
            UTCDateTime(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raffle_tickets")
    op.drop_table("changelog")
    op.drop_table("members")
    # ### end Alembic commands ###
