"""Use BigInteger for discord_id and ingot columns

Revision ID: 5ff107091ea1
Revises: 5588232465b1
Create Date: 2025-08-02 12:43:53.106557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5ff107091ea1"
down_revision: Union[str, None] = "5588232465b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.alter_column(
            "discord_id",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "ingots",
            existing_type=mysql.INTEGER(display_width=11),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.alter_column(
            "ingots",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "discord_id",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(display_width=11),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
