"""add score history table

Revision ID: d5f14e972bdd
Revises: 5ff107091ea1
Create Date: 2025-08-08 13:05:30.165926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f14e972bdd'
down_revision: Union[str, None] = '5ff107091ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=12), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('date', ironforgedbot.models.decorators.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_history')
    # ### end Alembic commands ###
