"""remove unique constraint from score history nickname column

Revision ID: ff14108b4c64
Revises: d5f14e972bdd
Create Date: 2025-08-08 13:22:05.862078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff14108b4c64'
down_revision: Union[str, None] = 'd5f14e972bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nickname'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nickname'), ['nickname'], unique=True)

    # ### end Alembic commands ###
