name: bump-version

on:
    workflow_call:

permissions:
    contents: write

jobs:
    bump_version:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Should bump version
              run: |
                  bump="false"
                  version1=$(cat VERSION | sed 's/^v//')
                  version2=$(git describe --tags --abbrev=0 | sed 's/^v//')

                  if [[ "$version1" == "$version2" ]]; then
                        echo "PR version and live version are equal, will bump."
                        bump="true"
                  elif [[ "$(printf '%s\n' "$version1" "$version2" | sort -V | head -n1)" == "$version1" ]]; then
                        echo "Live version $version2 is higher than PR version $version1. Update pull request and try again, aborting."
                        exit 1
                  else
                        echo "PR version $version1 is higher than live version $version2, looks like we already bumped, won't try again."
                        bump="false"
                  fi

                  echo "Bumping: $bump"
                  echo "SHOULD_BUMP=$bump" >> $GITHUB_ENV

            - name: Determine bump type
              id: get_bump_type
              if: env.SHOULD_BUMP == 'true'
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  REPO=${{ github.repository }}
                  RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                                  "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels")
                  echo "Labels: $RESPONSE"

                  if echo "$RESPONSE" | grep -q '"name": "major version"'; then
                    echo "BUMP_TYPE=major" >> $GITHUB_ENV
                  elif echo "$RESPONSE" | grep -q '"name": "minor version"'; then
                    echo "BUMP_TYPE=minor" >> $GITHUB_ENV
                  elif echo "$RESPONSE" | grep -q '"name": "patch version"'; then
                    echo "BUMP_TYPE=patch" >> $GITHUB_ENV
                  else
                    echo "No version label detected, not bumping version number."
                    echo "BUMP_TYPE=NONE" >> $GITHUB_ENV
                    echo "SHOULD_BUMP='false'" >> $GITHUB_ENV
                  fi

            - name: Set up Python
              uses: actions/setup-python@v5
              if: env.SHOULD_BUMP == 'true'
              with:
                  python-version: "3.x"

            - name: Install dependencies
              if: env.SHOULD_BUMP == 'true'
              run: |
                  python -m pip install --upgrade pip
                  pip install bump2version

            - name: Configure git
              if: env.SHOULD_BUMP == 'true'
              run: |
                  BRANCH_NAME=${{ github.head_ref }}

                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"

                  git checkout -b $BRANCH_NAME || git checkout $BRANCH_NAME
                  git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME
                  git pull origin $BRANCH_NAME

            - name: Bump version
              if: env.SHOULD_BUMP == 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  bump2version $BUMP_TYPE
                  git push origin $BRANCH_NAME
