name: ci-cd

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    packages: write

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    build-and-publish:
        needs: unit-test
        uses: ./.github/workflows/publish.yml

    staging-deploy:
        needs: build-and-publish
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: staging
        secrets: inherit

    release:
        needs: staging-deploy
        uses: ./.github/workflows/release.yml

    prod-deploy:
        needs: release
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: prod
        secrets: inherit
