name: ci-cd

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: write

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    tag-release:
        needs: unit-test
        permissions:
            contents: write
        uses: ./.github/workflows/tag-release.yml

    staging-deploy:
        needs: tag-release
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: staging

    live-deploy:
        needs: staging-deploy
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-environment.yml
        with:
            environment: live
