name: Promote staging image to latest

on:
  workflow_call:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/ironforgedclan/ironforgedbot

jobs:
  push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment: prod

    steps:
      - name: Generate App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SUBMODULE_APP_ID }}
          private-key: ${{ secrets.SUBMODULE_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: recursive

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest build
        run: docker pull ${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Tag as latest
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.IMAGE_NAME }}:latest

      - name: Push latest tag to registry
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest

