name: Promote staging image to latest

on:
  workflow_call:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/IronForgedClan/IronForgedBot

jobs:
  push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image as latest
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.IMAGE_NAME }}:latest

      - name: Push image to registry
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest

