name: pull-request

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    formatting:
        uses: ./.github/workflows/formatting.yml

