name: pull-request

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    formatting:
        uses: ./.github/workflows/formatting.yml

    version-check:
        uses: ./.github/workflows/version-check.yml

