name: pull-request

on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - reopened
            - submitted

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    formatting:
        needs: unit-test
        uses: ./.github/workflows/formatting.yml

    bump-version:
        needs: formatting
        if: github.event.review.state == 'approved'
        permissions:
            contents: write
        uses: ./.github/workflows/bump-version.yml
