name: pull-request

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

defaults:
    run:
        shell: bash

jobs:
    unit-test:
        uses: ./.github/workflows/unit-test.yml

    formatting:
        needs: unit-test
        uses: ./.github/workflows/formatting.yml

    bump-version-approval-gate:
        needs: formatting
        on: ubuntu-latest
        steps:
            - name: approved
                run: write-host "Approved for version bump"

    bump-version:
        needs: bump-version-approval-gate
        permissions:
            contents: write
        uses: ./.github/workflows/bump-version.yml
