name: pull-request

on:
    pull_request:
        branches: [main]

jobs:
    unit-test:
        uses: ./github/workflows/unit-test.yml

    formatting:
        needs: unit-test
        uses: ./github/workflows/formatting.yml

    bump-version:
        needs: formatting
        uses: ./github/workflows/bump-version.yml
