name: unit-test

on:
    workflow_call:

jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Generate App token
              id: app-token
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ secrets.SUBMODULE_APP_ID }}
                  private-key: ${{ secrets.SUBMODULE_APP_PRIVATE_KEY }}

            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  submodules: recursive

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"
                  architecture: "x64"

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: python run_tests.py
