name: unit-test

on:
    workflow_call:

jobs:
    run-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Generate App token
              id: app-token
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ secrets.SUBMODULE_APP_ID }}
                  private-key: ${{ secrets.SUBMODULE_APP_PRIVATE_KEY }}
                  repositories: |
                      IronForgedBot
                      IronForgedBot_Data

            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  submodules: recursive

            - name: Install uv
              uses: astral-sh/setup-uv@v1
              with:
                  version: "0.12.1"

            - name: Check lock is in sync
              run: uv lock --check --directory ironforgedbot

            - name: Build dev image
              run: docker compose build bot

            - name: Run tests
              run: docker compose run --rm --no-deps bot python run_tests.py
